[2025-01-13T19:06:55.993-0500] {processor.py:186} INFO - Started process (PID=48851) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T19:06:55.995-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-13T19:06:55.996-0500] {logging_mixin.py:190} INFO - [2025-01-13T19:06:55.996-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T19:06:56.026-0500] {logging_mixin.py:190} INFO - [2025-01-13T19:06:56.025-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-13T19:06:56.026-0500] {logging_mixin.py:190} INFO - [2025-01-13T19:06:56.026-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-13T19:06:56.026-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T19:06:56.172-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.183 seconds
[2025-01-13T19:09:31.820-0500] {processor.py:186} INFO - Started process (PID=50718) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T19:09:31.821-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-13T19:09:31.822-0500] {logging_mixin.py:190} INFO - [2025-01-13T19:09:31.822-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T19:09:31.852-0500] {logging_mixin.py:190} INFO - [2025-01-13T19:09:31.852-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-13T19:09:31.853-0500] {logging_mixin.py:190} INFO - [2025-01-13T19:09:31.852-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-13T19:09:31.853-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T19:09:31.993-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.177 seconds
[2025-01-13T20:01:05.228-0500] {processor.py:186} INFO - Started process (PID=55295) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T20:01:05.230-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-13T20:01:05.231-0500] {logging_mixin.py:190} INFO - [2025-01-13T20:01:05.231-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T20:01:05.265-0500] {logging_mixin.py:190} INFO - [2025-01-13T20:01:05.264-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-13T20:01:05.265-0500] {logging_mixin.py:190} INFO - [2025-01-13T20:01:05.265-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-13T20:01:05.266-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T20:01:05.413-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.189 seconds
